# Generated by Django 4.2.4 on 2023-09-06 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 18, 5, 29, 98687, tzinfo=datetime.timezone.utc), editable=False, null=True),
        ),
    ]
