# Generated by Django 4.2.4 on 2023-09-06 12:23

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_verification_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 9, 6, 20, 23, 7, 526012, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 20, 23, 7, 525863, tzinfo=datetime.timezone.utc), editable=False, null=True),
        ),
    ]
