# Generated by Django 4.2.4 on 2023-10-23 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_customuser_reset_password_token_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reset_password_token_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 24, 2, 12, 4, 981240, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verification_token_expiration',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 24, 2, 12, 4, 981179, tzinfo=datetime.timezone.utc), editable=False, null=True),
        ),
    ]
