# Generated by Django 4.2.4 on 2023-09-23 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_uniqueid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='uniqueid',
            new_name='unique_id',
        ),
    ]
