# Generated by Django 4.2.4 on 2023-09-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_uniqueid_task_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='thumbnail_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
